server {
    listen 80;
    server_name timur.aboard.ru;

    root /usr/share/nginx/html;

    index index.html;

    error_page 404 /404.html;

    location /credit-helper/ {
        proxy_pass http://host.docker.internal:9001/;
        proxy_set_header Host $host;
        rewrite ^/credit-helper(/.*)$ $1 break;
    }

    location /foodgram/ {
        proxy_pass http://host.docker.internal:9002/;
        proxy_set_header Host $host;
        rewrite ^/foodgram(/.*)$ $1 break;
    }

    location /grocket/ {
        proxy_pass http://host.docker.internal:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/grocket(/.*)$ $1 break;
    }

    location /grocket/ws/ {
        proxy_pass http://host.docker.internal:8001/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        rewrite ^/grocket/ws/(.*)$ /ws/$1 break;
    }

    location /collabra/ {
        proxy_pass http://host.docker.internal:8241/;
        proxy_set_header Host $host;
        rewrite ^/collabra(/.*)$ $1 break;
    }
}
